default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_development

test:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] %>_test

production:
  primary: &primary_production
    <<: *default
    database: <%= ENV['DATABASE_NAME'] %>_production
    username: <%= ENV['DATABASE_USERNAME'] %>
    password: <%= ENV['SHOP_API_DATABASE_PASSWORD'] %>
  cache:
    <<: *primary_production
    database: <%= ENV['DATABASE_NAME'] %>_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: <%= ENV['DATABASE_NAME'] %>_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: <%= ENV['DATABASE_NAME'] %>_production_cable
    migrations_paths: db/cable_migrate
